name: Deploy to GitHub Pages

on:
  # main 브랜치에 푸시될 때마다 워크플로우 실행
  push:
    branches: [ main ]
  # 수동으로 실행 가능
  workflow_dispatch:

# GITHUB_TOKEN 권한 설정
permissions:
  contents: read
  pages: write
  id-token: write

# 동시 빌드 방지
concurrency:
  group: pages-${{ github.ref }}
  cancel-in-progress: true

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: 저장소 체크아웃
        uses: actions/checkout@v4
        with:
          fetch-depth: 0 # 전체 히스토리 가져오기 (lastModified 기능 지원)

      - name: Node.js 설정
        uses: actions/setup-node@v4
        with:
          node-version: '18'
          cache: 'npm'

      - name: 의존성 설치
        run: npm ci

      - name: 빌드
        run: npm run build

      - name: Pages 아티팩트 업로드
        uses: actions/upload-pages-artifact@v3
        with:
          path: dist # Astro 기본 빌드 출력 디렉토리

  deploy:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: GitHub Pages에 배포
        id: deployment
        uses: actions/deploy-pages@v4
